export const FETCH_SHOWS = 'FETCH_SHOWS'; 
export const SEARCH_ICON_CLICKED = 'SEARCH_ICON_CLICKED' 
export const SEARCH_BAR_TEXT_CHANGED = 'SEARCH_BAR_TEXT_CHANGED'; 
export const FETCH_FILTER_SHOWS = 'FETCH_FILTER_SHOWS';
export const INIT_PAGE_NUMBER = 'INIT_PAGE_NUMBER'
export const CLEAR_FILTER_DATA = 'CLEAR_FILTER_DATA'

